// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        return linux;

      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

case TargetPlatform.macOS:
  throw UnsupportedError(
    'DefaultFirebaseOptions have not been configured for macOS. '
    'You can reconfigure this by running the FlutterFire CLI again.',
  );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyDhzYaDsaIjr2drU5Vm21gac9GOHFOWX28",
  authDomain: "pdm-alecrim.firebaseapp.com",
  projectId: "pdm-alecrim",
  storageBucket: "pdm-alecrim.firebasestorage.app",
  messagingSenderId: "52488192701",
  appId: "1:52488192701:web:60dbed8ce6e2f9992dadd4"
  );

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: "AIzaSyDhzYaDsaIjr2drU5Vm21gac9GOHFOWX28",
  authDomain: "pdm-alecrim.firebaseapp.com",
  projectId: "pdm-alecrim",
  storageBucket: "pdm-alecrim.firebasestorage.app",
  messagingSenderId: "52488192701",
  appId: "1:52488192701:web:60dbed8ce6e2f9992dadd4"
  );

  static const FirebaseOptions linux = FirebaseOptions(
     apiKey: "AIzaSyDhzYaDsaIjr2drU5Vm21gac9GOHFOWX28",
  authDomain: "pdm-alecrim.firebaseapp.com",
  projectId: "pdm-alecrim",
  storageBucket: "pdm-alecrim.firebasestorage.app",
  messagingSenderId: "52488192701",
  appId: "1:52488192701:web:60dbed8ce6e2f9992dadd4"
  );

  static const FirebaseOptions windows = FirebaseOptions(
   apiKey: "AIzaSyDhzYaDsaIjr2drU5Vm21gac9GOHFOWX28",
  authDomain: "pdm-alecrim.firebaseapp.com",
  projectId: "pdm-alecrim",
  storageBucket: "pdm-alecrim.firebasestorage.app",
  messagingSenderId: "52488192701",
  appId: "1:52488192701:web:60dbed8ce6e2f9992dadd4"
  );
}